export const organizations = [
    {
        orgHandle: "org1",
        name: "PawsOrg",
        motto: "We love animals",
        description: "We are a non-profit organization that helps animals in need.",
        address: "1234 Main St, Anytown, USA",
        email: "paws@gmail.com",
        phone: "123-456-7890",
        rating: 4.5,
        reviews: [{
            userHandle: "user1",
            rating: 5,
            review: "Great organization!",
        },
        {
            userHandle: "user2",
            rating: 4,
            review: "Good organization!",
        }],
        followers: 1000,
        banner: "/images/banner.jpg",
        profile: "/images/profile.jpg",
        images: ["/images/dog.jpg", "/images/dog.jpg"],
        pets: [1, 2, 3, 4, 5, 6],
    },
    {
        orgHandle: "org2",
        name: "PawsOrg",
        motto: "We love animals",
        description: "We are a non-profit organization that helps animals in need.",
        address: "1234 Main St, Anytown, USA",
        email: "paws@gmail.com",
        phone: "123-456-7890",
        rating: 4.5,
        reviews: [],
        followers: 1000,
        banner: "/images/banner.jpg",
        profile: "/images/profile.jpg",
        images: ["/images/dog.jpg", "/images/dog.jpg"],
        pets: [1, 2, 3, 4],
    },
    {
        orgHandle: "org3",
        name: "PawsOrg",
        motto: "We love animals",
        description: "We are a non-profit organization that helps animals in need.",
        address: "1234 Main St, Anytown, USA",
        email: "paws@gmail.com",
        phone: "123-456-7890",
        rating: 4.5,
        reviews: [],
        followers: 1000,
        banner: "/images/banner.jpg",
        profile: "/images/profile.jpg",
        images: ["/images/dog.jpg", "/images/dog.jpg"],
        pets: [1, 2, 3, 4],
    },
    {
        orgHandle: "org4",
        name: "PawsOrg",
        motto: "We love animals",
        description: "We are a non-profit organization that helps animals in need.",
        address: "1234 Main St, Anytown, USA",
        email: "paws@gmail.com",
        phone: "123-456-7890",
        rating: 4.5,
        reviews: 100,
        followers: 1000,
        banner: "/images/banner.jpg",
        profile: "/images/profile.jpg",
        images: ["/images/dog.jpg", "/images/dog.jpg"],
        pets: [1, 2, 3, 4],
    },
    {
        orgHandle: "org5",
        name: "PawsOrg",
        motto: "We love animals",
        description: "We are a non-profit organization that helps animals in need.",
        address: "1234 Main St, Anytown, USA",
        email: "org5",
        phone: "123-456-7890",
        rating: 4.5,
        reviews: 100,
        followers: 1000,
        banner: "/images/banner.jpg",
        profile: "/images/profile.jpg",
        images: ["/images/dog.jpg", "/images/dog.jpg"],
        pets: [1, 2, 3, 4],
    },
]

export const getOrganization = (orgHandle) => {
    return organizations.find(org => org.orgHandle === orgHandle);
}